### ISSUE TITLE
content-server error invalid character

### ISSUE THREAD

**Issue by erSitzt** [criticalstack/quake-kube#3]
Hi,

any idea where this error is coming from when the content-server starts ?

```
Error: invalid character '<' looking for beginning of value
2020/08/05 10:27:44 invalid character '<' looking for beginning of value
````

**Comment by ChrisRx** [comment]
I suspect it is coming from here:  https://github.com/criticalstack/quake-kube/blob/13d35f17f16733393de7ea008f9d4512df02293f/internal/quake/content/download.go#L55-L66

Where the data being returned from the content-server `seed-content-url` that was specified is returning something that includes a `<` as the first character, where it is trying to parse json.  I've started cleaning this part up so that it will at least give a better error when this happens, but I think it is the content-server `seed-content-url` that it is getting not being available or having an invalid `${seed-content-url}/assets/manifest.json`.

**Comment by erSitzt** [comment]
Thanks, with the error message i could see that a content filter was blocking the request :)

**Comment by ChrisRx** [comment]
That's great!  I'll close this one, but if it didn't fully address the issue, feel free to reopen the issue.  Thanks again for reporting this!
